### ISSUE TITLE
Install fail - missing postgresql-13-postgis-3 dependency

### ISSUE THREAD

**Issue by mediaformat** [YunoHost-Apps/mobilizon_ynh#35]
Installation of Mobilizon has failed! 
Here is the end of the logfile.
```
2019-11-13 23:14:40,826: DEBUG - 
2019-11-13 23:14:40,827: DEBUG - 23:14:40.800 [info]  == Running 20180109150000 Mobilizon.Repo.Migrations.Prerequites.up/0 forward
2019-11-13 23:14:40,827: DEBUG - 
2019-11-13 23:14:40,827: DEBUG - 23:14:40.801 [info]  execute "CREATE TYPE datetimetz AS (\n    dt timestamptz,\n    tz varchar\n);\n"
2019-11-13 23:14:40,827: DEBUG - 
2019-11-13 23:14:40,828: DEBUG - 23:14:40.815 [info]  execute "CREATE EXTENSION IF NOT EXISTS postgis"
2019-11-13 23:14:40,928: DEBUG - + ynh_exit_properly
2019-11-13 23:14:40,929: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
2019-11-13 23:14:40,934: DEBUG - + local exit_code=1
```

**Comment by mediaformat** [comment]
Just retried with the latest version, looks like the same postgis error.

I'll 

```
2019-12-21 17:47:28,652: DEBUG - Generated mobilizon app
2019-12-21 17:47:48,097: DEBUG - 
2019-12-21 17:47:48,098: DEBUG - 
2019-12-21 17:47:48,098: DEBUG -     #########################################################
2019-12-21 17:47:48,098: DEBUG -     # If the CREATE EXTENSION or DROP EXTENSION calls fail, #
2019-12-21 17:47:48,099: DEBUG -     # please manually execute them with an authorized       #
2019-12-21 17:47:48,099: DEBUG -     # PostgreSQL user with SUPER USER role.                 #
2019-12-21 17:47:48,100: DEBUG -     #########################################################
2019-12-21 17:47:48,100: DEBUG - 
2019-12-21 17:47:48,100: DEBUG - 
2019-12-21 17:47:48,100: DEBUG - 
2019-12-21 17:47:48,101: DEBUG - 
2019-12-21 17:47:48,102: DEBUG - 17:47:48.071 [info]  == Running 20180109150000 Mobilizon.Repo.Migrations.Prerequites.up/0 forward
2019-12-21 17:47:48,102: DEBUG - 
2019-12-21 17:47:48,102: DEBUG - 17:47:48.073 [info]  execute "CREATE TYPE datetimetz AS (\n    dt timestamptz,\n    tz varchar\n);\n"
2019-12-21 17:47:48,303: DEBUG - 
2019-12-21 17:47:48,303: DEBUG - 17:47:48.280 [info]  execute "CREATE EXTENSION IF NOT EXISTS postgis"
2019-12-21 17:47:48,605: DEBUG - + ynh_exit_properly
2019-12-21 17:47:48,605: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
2019-12-21 17:47:48,608: DEBUG - + local exit_code=1
2019-12-21 17:47:48,608: DEBUG - + '[' 1 -eq 0 ']'
2019-12-21 17:47:48,609: DEBUG - + trap '' EXIT
2019-12-21 17:47:48,609: DEBUG - + set +eu
2019-12-21 17:47:48,609: DEBUG - + sleep 0.5
2019-12-21 17:47:48,710: WARNING -     (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
2019-12-21 17:47:48,711: WARNING -     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
2019-12-21 17:47:48,712: WARNING -     (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
2019-12-21 17:47:48,713: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
2019-12-21 17:47:48,714: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
2019-12-21 17:47:48,714: WARNING -     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
2019-12-21 17:47:48,715: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
2019-12-21 17:47:48,716: WARNING -     (stdlib) timer.erl:166: :timer.tc/1
2019-12-21 17:47:49,218: DEBUG - + ynh_print_err '--message=!!\n  mobilizon'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-12-21 17:47:49,218: DEBUG - + local legacy_args=m
2019-12-21 17:47:49,218: DEBUG - + args_array=([m]=message=)
2019-12-21 17:47:49,218: DEBUG - + declare -Ar args_array
2019-12-21 17:47:49,219: DEBUG - + local message
2019-12-21 17:47:49,219: DEBUG - + ynh_handle_getopts_args '--message=!!\n  mobilizon'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-12-21 17:47:49,219: DEBUG - + set +x
2019-12-21 17:47:49,520: DEBUG - + ynh_print_log '\e[91m\e[1m[ERR]\e[0m !!\n  mobilizon'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-12-21 17:47:49,520: WARNING - [91m[1m[ERR][0m !!
2019-12-21 17:47:49,521: DEBUG - + echo -e '\e[91m\e[1m[ERR]\e[0m !!\n  mobilizon'\''s script has encountered an error. Its execution was cancelled.\n!!'
2019-12-21 17:47:49,521: WARNING -   mobilizon's script has encountered an error. Its execution was cancelled.
2019-12-21 17:47:49,521: DEBUG - + '[' api == cli ']'
2019-12-21 17:47:49,521: WARNING - !!
2019-12-21 17:47:49,522: DEBUG - + type -t ynh_clean_setup
2019-12-21 17:47:49,522: WARNING - 
2019-12-21 17:47:49,522: DEBUG - + ynh_clean_setup
2019-12-21 17:47:49,522: DEBUG - + ynh_clean_check_starting
2019-12-21 17:47:49,523: DEBUG - + kill -s 15
2019-12-21 17:47:49,523: DEBUG - kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
2019-12-21 17:47:49,523: DEBUG - + ynh_secure_remove ''
2019-12-21 17:47:49,523: DEBUG - + local legacy_args=f
2019-12-21 17:47:49,523: DEBUG - + args_array=([f]=file=)
2019-12-21 17:47:49,523: DEBUG - + declare -Ar args_array
2019-12-21 17:47:49,523: DEBUG - + local file
2019-12-21 17:47:49,524: DEBUG - + ynh_handle_getopts_args ''
2019-12-21 17:47:49,524: DEBUG - + set +x
2019-12-21 17:47:49,524: DEBUG - + echo '! Helper used in legacy mode !'
2019-12-21 17:47:49,524: DEBUG - + set +x
2019-12-21 17:47:49,524: DEBUG - + local 'forbidden_path=     /var/www     /home/yunohost.app'
2019-12-21 17:47:49,524: DEBUG - + '[' 1 -ge 2 ']'
2019-12-21 17:47:49,525: DEBUG - + [[      /var/www     /home/yunohost.app =~ '' ]]
2019-12-21 17:47:49,525: DEBUG - + ynh_print_warn '--message=Avoid deleting .'
2019-12-21 17:47:49,525: DEBUG - + local legacy_args=m
2019-12-21 17:47:49,525: DEBUG - + args_array=([m]=message=)
2019-12-21 17:47:49,526: DEBUG - + declare -Ar args_array
2019-12-21 17:47:49,526: DEBUG - + local message
2019-12-21 17:47:49,526: DEBUG - + ynh_handle_getopts_args '--message=Avoid deleting .'
2019-12-21 17:47:49,526: DEBUG - + set +x
2019-12-21 17:47:49,526: DEBUG - + ynh_print_log '\e[93m\e[1m[WARN]\e[0m Avoid deleting .'
2019-12-21 17:47:49,526: DEBUG - + echo -e '\e[93m\e[1m[WARN]\e[0m Avoid deleting .'
2019-12-21 17:47:49,527: DEBUG - [93m[1m[WARN][0m Avoid deleting .
2019-12-21 17:47:49,527: DEBUG - + ynh_die
2019-12-21 17:47:49,527: DEBUG - + local legacy_args=mc
2019-12-21 17:47:49,527: DEBUG - + args_array=([m]=message= [c]=ret_code=)
2019-12-21 17:47:49,527: DEBUG - + declare -Ar args_array
2019-12-21 17:47:49,527: DEBUG - + local message
2019-12-21 17:47:49,528: DEBUG - + local ret_code
2019-12-21 17:47:49,528: DEBUG - + ynh_handle_getopts_args
2019-12-21 17:47:49,528: DEBUG - + set +x
2019-12-21 17:47:49,528: DEBUG - + echo ''
2019-12-21 17:47:49,528: DEBUG - + exit 1
```

**Comment by yalh76** [comment]
On want kind of YunoHost are you ?

**Comment by mediaformat** [comment]
Debian 9

**Comment by mediaformat** [comment]
Sorry I am not familiar with Python, it seems something is happening between line 303, if postgis doesn't exist, and line 605 where it can't be found. 
```
2019-12-21 17:47:48,303: DEBUG - 17:47:48.280 [info]  execute "CREATE EXTENSION IF NOT EXISTS postgis"
2019-12-21 17:47:48,605: DEBUG - + ynh_exit_properly
2019-12-21 17:47:48,605: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
```

**Comment by yalh76** [comment]
> 
> 
> Debian 9

But a Raspberry Pi ? Virtual Machine ? 64 or 32 bits ?

**Comment by yalh76** [comment]
> 
> 
> Sorry I am not familiar with Python, it seems something is happening between line 303, if postgis doesn't exist, and line 605 where it can't be found.
> 
> ```
> 2019-12-21 17:47:48,303: DEBUG - 17:47:48.280 [info]  execute "CREATE EXTENSION IF NOT EXISTS postgis"
> 2019-12-21 17:47:48,605: DEBUG - + ynh_exit_properly
> 2019-12-21 17:47:48,605: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
> ```

I don't understand, what is line 303 or 605... Mobilizon install script only has 255 lines...

BTW: install script are bash not python...

**Comment by mediaformat** [comment]
> But a Raspberry Pi ? Virtual Machine ? 64 or 32 bits ?

Oh, its an ovh VPS, I am guessing its 64bit !


> I don't understand, what is line 303 or 605... Mobilizon install script only has 255 lines...

The lines I was referring to are the debug lines:
> ```
> 303: DEBUG - 17:47:48.280 [info]  execute "CREATE EXTENSION IF NOT EXISTS postgis"
> 605: DEBUG - + ynh_exit_properly
> 605: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
> ```

Not sure why it's not downloading, or installing, perhaps a debug check with pg_available_extensions...

**Comment by yalh76** [comment]
Or maybe something related to OVH VMs, already seen something on [peertube_ynh](https://github.com/YunoHost-Apps/peertube_ynh/tree/ovh_fix)

**Comment by yalh76** [comment]
What is the result for `find / -name postgis.control`

**Comment by yalh76** [comment]
Without news, I close that issue. Feel free to reopen that issue

**Comment by loppear** [comment]
Got this error on fresh install today (`execute "CREATE EXTENSION IF NOT EXISTS postgis"` and install fails) on Debian 11.

Installing the postgis libraries with `apt install postgresql-13-postgis-3` before install corrected the issue and allowed install to proceed.

**Comment by rodinux** [comment]
> Got this error on fresh install today (`execute "CREATE EXTENSION IF NOT EXISTS postgis"` and install fails) on Debian 11.
> 
> Installing the postgis libraries with `apt install postgresql-13-postgis-3` before install corrected the issue and allowed install to proceed.

Can you confirm your instance is working ?? I have problems with sign up on mine...

**Comment by loppear** [comment]
I don't have registration enabled on my test instance here, but this did succeed to the point of the admin user logging in, new events and groups being created, so I would lean towards creating a separate issue to sort out post-install issues with sign up in your case.

**Comment by yashodhank** [comment]
> Got this error on fresh install today (`execute "CREATE EXTENSION IF NOT EXISTS postgis"` and install fails) on Debian 11.
> 
> Installing the postgis libraries with `apt install postgresql-13-postgis-3` before install corrected the issue and allowed install to proceed.

I have installed after installation failed and it worked as described! Thank you..

**Comment by mediaformat** [comment]
Digging in a bit deeper here. 

```
# dependencies used by the app
pkg_dependencies="postgresql postgresql-client postgresql-contrib postgis postgresql-postgis-scripts argon2 imagemagick webp gifsicle jpegoptim optipng pngquant file"
```
So [postgresql-postgis-scripts](https://packages.debian.org/bullseye/postgresql-postgis-scripts) is an alias for 


The question then is why aren't the dependenci
postgresql-postgis-scripts

https://github.com/YunoHost-Apps/mobilizon_ynh/blob/master/scripts/install#L74-L79
