### ISSUE TITLE
fail to install... dependency postgis`of postgres

### ISSUE THREAD

**Issue by albjeremias** [YunoHost-Apps/mobilizon_ynh#39]
```
warning: warning: function Phoenix.View.render_to_string/3 is undefined (module Phoenix.View is not available)
Warning: Found at 2 locations:
Warning:   lib/bamboo/phoenix.ex:313
Warning:   lib/bamboo/phoenix.ex:323
Warning: 
Warning: ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
Warning:     (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
Warning:     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
Warning:     (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
Warning:     (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
Warning:     (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
Warning:     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
Warning:     (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
Warning:     (stdlib) timer.erl:166: :timer.tc/1
Warning: [ERR] !!
Warning:   mobilizon's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: Please find here an extract of the log before the crash:
Warning: [DEBUG]: WARNING - ** (Postgrex.Error) ERROR 58P01 (undefined_file) could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
Warning: [DEBUG]: DEBUG   -     #########################################################
Warning: [DEBUG]: WARNING -     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
Warning: [DEBUG]: DEBUG   -     # If the CREATE EXTENSION or DROP EXTENSION calls fail, #
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
Warning: [DEBUG]: DEBUG   -     # please manually execute them with an authorized       #
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
Warning: [DEBUG]: DEBUG   -     # PostgreSQL user with SUPER USER role.                 #
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
Warning: [DEBUG]: DEBUG   -     #########################################################
Warning: [DEBUG]: WARNING -     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (stdlib) timer.erl:166: :timer.tc/1
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -  == Running 20180109150000 Mobilizon.Repo.Migrations.Prerequites.up/0 forward
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -  execute "CREATE TYPE datetimetz AS (
Warning:     dt timestamptz,
Warning:     tz varchar
Warning: );
Warning: "
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -  execute "CREATE EXTENSION IF NOT EXISTS postgis"
Warning: [DEBUG]: DEBUG   - + ynh_exit_properly
Warning: 
Info: The operation 'Install 'mobilizon' application' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20191127-233501-app_install-mobilizon --share'
```

**Comment by albjeremias** [comment]
ok.. i installed postgis manually.. 

`apt install postgresql-9.6-postgis-scripts`

got a new error.

```
Warning: warning: System.stacktrace/0 outside of rescue/catch clauses is deprecated. If you want to support only Elixir v1.7+, you must access __STACKTRACE__ inside a rescue/catch. If you want to support earlier Elixir versions, move System.stacktrace/0 inside a rescue/catch
Warning:   lib/plug/conn/wrapper_error.ex:23
Warning: 
Warning: warning: function Phoenix.View.render_to_string/3 is undefined (module Phoenix.View is not available)
Warning: Found at 2 locations:
Warning:   lib/bamboo/phoenix.ex:313
Warning:   lib/bamboo/phoenix.ex:323
Warning: 
Warning: ** (Postgrex.Error) ERROR 42501 (insufficient_privilege) permission denied to create extension "postgis"
Warning: 
Warning:     hint: Must be superuser to create this extension.
Warning:     (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
Warning:     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
Warning:     (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
Warning:     (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
Warning:     (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
Warning:     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
Warning:     (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
Warning:     (stdlib) timer.erl:166: :timer.tc/1
Warning: [ERR] !!
Warning:   mobilizon's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: Please find here an extract of the log before the crash:
Warning: [DEBUG]: WARNING -
Warning: [DEBUG]: DEBUG   -     #########################################################
Warning: [DEBUG]: WARNING -     hint: Must be superuser to create this extension.
Warning: [DEBUG]: DEBUG   -     # If the CREATE EXTENSION or DROP EXTENSION calls fail, #
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/adapters/sql.ex:621: Ecto.Adapters.SQL.raise_sql_call_error/1
Warning: [DEBUG]: DEBUG   -     # please manually execute them with an authorized       #
Warning: [DEBUG]: WARNING -     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
Warning: [DEBUG]: DEBUG   -     # PostgreSQL user with SUPER USER role.                 #
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/adapters/sql.ex:708: Ecto.Adapters.SQL.execute_ddl/4
Warning: [DEBUG]: DEBUG   -     #########################################################
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:340: Ecto.Migration.Runner.log_and_execute_ddl/3
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:119: anonymous fn/6 in Ecto.Migration.Runner.flush/0
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (ecto_sql) lib/ecto/migration/runner.ex:118: Ecto.Migration.Runner.flush/0
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: WARNING -     (stdlib) timer.erl:166: :timer.tc/1
Warning: [DEBUG]: DEBUG   -  == Running 20180109150000 Mobilizon.Repo.Migrations.Prerequites.up/0 forward
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -  execute "CREATE TYPE datetimetz AS (
Warning:     dt timestamptz,
Warning:     tz varchar
Warning: );
Warning: "
Warning: [DEBUG]: DEBUG   -
Warning: [DEBUG]: DEBUG   -  execute "CREATE EXTENSION IF NOT EXISTS postgis"
Warning: [DEBUG]: DEBUG   - + ynh_exit_properly
Warning: 
Info: The operation 'Install 'mobilizon' application' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20191128-084930-app_install-mobilizon --share'
Info: Loading installation settings...
Info: Stopping and removing the systemd service
Info: Removing the PostgreSQL database
Warning: FATAL:  terminating connection due to administrator command
Warning: server closed the connection unexpectedly
Warning: 	This probably means the server terminated abnormally
Warning: 	before or while processing the request.
Warning: connection to server was lost
Info: Removing dependencies
Info: Removing app main directory
Info: Removing nginx web server configuration
Warning: [WARN] Avoid deleting /var/log/mobilizon/.
Info: Closing a port...
Info: Removing the dedicated system user
Info: Removal of mobilizon completed
Success! The SSOwat configuration has been generated
Error: The operation 'Install 'mobilizon' application' has failed! To get help, please share the full log of this operation using the command 'yunohost log display 20191128-084930-app_install-mobilizon --share'
```

**Comment by yalh76** [comment]
In the install script postgis is installed using : `sudo apt install postgis`

**Comment by yalh76** [comment]
Feel free to reopen that issue
